
spring:
server:
  port: 7171
  ssl:
    certificate-private-key: "classpath:key.pem"
    certificate: "classpath:cert.pem"


#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#    username: root
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false
#    show-sql: false
#    hibernate:
#      format_sql: true
#      ddl-auto: update
#    properties:
#      hibernate.default_batch_fetch_size: 1000